config/routes.rb
Rails.application.routes.draw do
  root 'coaches#index'

  resources :coaches, only: :index do
    member do
      get :calendar
      get 'availability_for_date/:date', action: :availability_for_date, as: :availability_for_date
    end

    resources :appointments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :coach

  VALID_MINUTES = [0, 30].freeze

  validates :email, presence: true, format: { with: /\A[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\z/, message: 'must be a valid format' }
  # 1 appointment for a coaches available time.
  validates :start_time, uniqueness: { scope: :coach_id }
  validate :start_time_in_future
  validate :start_time_has_valid_minute
  validate :within_coaches_availability

  scope :for_date_time_start, -> (date_time_start) { where(start_time: date_time_start...(date_time_start + 1.day)) }

  private

  def start_time_in_future
    errors.add(:start_time, "can't be in the past") unless start_time.future?
  end

  def start_time_has_valid_minute
    errors.add(:start_time, 'minute must be 0 or 30') unless VALID_MINUTES.include? start_time.min
  end

  def within_coaches_availability
    # TODO
  end
end

app/models/available_weekday.rb
class AvailableWeekday < ApplicationRecord
  belongs_to :coach

  VALID_MINUTES = [0, 30].freeze

  validates :weekday, presence: true, inclusion: { in: 0..6 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :times_have_valid_minute
  validate :end_time_greater_than_start_time
  validate :times_do_not_overlap

  private

  def times_have_valid_minute
    errors.add(:start_time, 'minute must be 0 or 30') unless VALID_MINUTES.include? start_time.min
    errors.add(:end_time, 'minute must be 0 or 30') unless VALID_MINUTES.include? end_time.min
  end

  def end_time_greater_than_start_time
    errors.add(:end_time, 'must be greater than start_time') unless end_time > start_time
  end

  def times_do_not_overlap
    if AvailableWeekday.where(coach_id: coach_id, weekday: weekday, start_time: start_time...end_time).present?
      errors.add(:start_time, 'must not fall within another available day')
    end
    if AvailableWeekday.where(coach_id: coach_id, weekday: weekday, end_time: start_time...end_time).present?
      errors.add(:end_time, 'must not fall within another available day')
    end
  end
end

app/models/coach.rb
class Coach < ApplicationRecord
  has_many :available_weekdays, dependent: :destroy
  has_many :appointments, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :time_zone, presence: true
  validates :time_zone_string, presence: true
  validate :valid_time_zone

  private

  def valid_time_zone
    errors.add(:time_zone, 'must be valid') unless ActiveSupport::TimeZone[time_zone].present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @coach = Coach.find(params[:coach_id])
    @appointment = @coach.appointments.build(start_time: params[:start_time])
  end

  def create
    @coach = Coach.find(params[:coach_id])
    @appointment = @coach.appointments.build(appointment_params)

    if @appointment.save
      flash.now[:notice] = 'Congratulations! You have booked an appointment.'
      render :show
    else
      render :new
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:email, :start_time)
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
    @coaches = Coach.order(:name)
  end

  def calendar
    @coach = Coach.find(params[:id])
    @weekdays = AvailableWeekday.where(coach: @coach).uniq.pluck(:weekday)
  end

  def availability_for_date
    @date = params[:date].to_date
    @coach = Coach.find(params[:id])
    @available_weekdays = AvailableWeekday.where(coach: @coach, weekday: @date.wday).order(:start_time)
    @date_in_zone = @date.in_time_zone(@coach.time_zone)

    @booked_appointment_start_times = @coach.appointments.for_date_time_start(@date_in_zone).pluck(:start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/new.html.slim
.container
  .row
    .col
      nav aria-label="breadcrumb"
        ol.breadcrumb
          li.breadcrumb-item aria-current="page"= link_to 'All Coaches', root_path
          li.breadcrumb-item aria-current="page"= link_to 'Calendar', calendar_coach_path(@coach)
          - availability_date_iso = @appointment.start_time.to_date.to_formatted_s(:iso8601)
          li.breadcrumb-item aria-current="page"= link_to "#{availability_date_iso} times", availability_for_date_coach_path(@coach, date: availability_date_iso)

  .row
    .col
      h1 Create Appointment for #{@coach.name}

      p
        b Time Zone:
        =< @coach.time_zone_string
      p
        b Date and Time:
        =< @appointment.start_time.in_time_zone(@coach.time_zone).to_formatted_s(:long_ordinal_with_period)

      - if @appointment.errors
        - @appointment.errors.full_messages.each do |msg|
          li= msg

      = simple_form_for [@coach, @appointment] do |f|
        = f.hidden_field :start_time
        = f.input :email
        = f.submit

      br
      = link_to 'Cancel', availability_for_date_coach_path(@coach, date: availability_date_iso)

app/views/appointments/show.html.slim
.container
  .row
    .col
      h1 Appointment with #{@coach.name}

      p
        b When:
        =< @appointment.start_time.in_time_zone(@coach.time_zone).to_formatted_s(:long_ordinal_with_period)

      p
        b Time Zone:
        =< @coach.time_zone_string

      p= link_to 'Back To All Coaches', root_path

app/views/coaches/availability_for_date.html.slim
.container
  .row
    .col
      nav aria-label="breadcrumb"
        ol.breadcrumb
          li.breadcrumb-item aria-current="page"= link_to 'All Coaches', root_path
          li.breadcrumb-item aria-current="page"= link_to 'Calendar', calendar_coach_path(@coach)

  .row
    .col
      h1 Available Times for #{@coach.name}
      b Time Zone:
      =< @coach.time_zone_string

      h3.mt-4 Date: #{@date.to_formatted_s(:long)}
      ul.list-group
        - @available_weekdays.each do |available_weekday|
          - (available_weekday.start_time.to_i...(available_weekday.end_time).to_i).step(30.minutes).each do |time_millis|
            - time_of_day = Time.at(time_millis)
            - datetime_in_zone = @date_in_zone + time_of_day.hour.hours + time_of_day.min.minutes
            li.list-group-item
              .row
                .col-3= time_of_day.strftime('%I:%M%p')
                .col-9
                  - if @booked_appointment_start_times.include? datetime_in_zone
                    b Unavailable
                  - else
                    = link_to 'Book Appointment', new_coach_appointment_path(@coach, start_time: datetime_in_zone)

app/views/coaches/calendar.html.slim
.container
  .row
    .col
      nav aria-label="breadcrumb"
        ol.breadcrumb
          li.breadcrumb-item aria-current="page"= link_to 'All Coaches', root_path

  .row
    .col
      h1 Available Days for #{@coach.name}
      b Time Zone:
      =< @coach.time_zone_string

      .mt-4
        = month_calendar do |date|
          div
            = date.day
            - if date.future? && @weekdays.include?(date.wday)
              p= link_to 'View hours', availability_for_date_coach_path(@coach, date: date.to_formatted_s(:iso8601))

app/views/coaches/index.html.slim
.container
  .row
    .col-12
      h4.my-4 Choose a Coach to view Availablity and schedule an appointment!

      table.table.table-striped
        tr
          th Name
          th Time Zone
          th Calendar
        - @coaches.each do |coach|
          tr
            td= coach.name
            td= coach.time_zone_string
            td= link_to 'Calendar', calendar_coach_path(coach)

app/views/layouts/application.html.slim
doctype html
html
  head
    title Coach Booking
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-expand-lg.navbar-light.bg-light
      a.navbar-brand href="/" Coach Booking

    - flash.each do |name, msg|
      = content_tag :div, msg, class: 'alert alert-info'

    = yield